### Create an article:
POST http://localhost:8080/api/v1/articles
Authorization: Basic admin admin
Content-Type: application/json

{
  "category": "Chemistry",
  "title": "The first Chemistry Article",
  "content": "It is very interesting to read the first ever article",
  "secondaryTitle": "Chemistry beyond the database",
  "mainImg": "something",
  "mainImgDescription": "some image",
  "mainImgCredit": "no credit"
}

### Get all the articles:
GET http://localhost:8080/api/v1/articles
Authorization: Basic dXNlcjpwYXNzd29yZA==

### Get an article by id:
GET http://localhost:8080/api/v1/articles/202
Authorization: Basic dXNlcjpwYXNzd29yZA==

###Update an article by id:
PUT http://localhost:8080/api/v1/articles/202
Authorization: Basic dXNlcjpwYXNzd29yZA==
Content-Type: application/json

{
  "category": "Chemistry",
  "title": "Changed!!!! The first Chemistry Article",
  "content": "It is very interesting to read the first ever article",
  "secondaryTitle": "Chemistry beyond the database",
  "mainImg": "something",
  "mainImgDescription": "some image",
  "mainImgCredit": "no credit"
}

###Get articles by page 1:
GET http://localhost:8080/api/v1/articles/page?pageSize=2&pageNo=0
Authorization: Basic dXNlcjpwYXNzd29yZA==


###Get articles by page 2:
GET http://localhost:8080/api/v1/articles/page?pageSize=2&pageNo=1
Authorization: Basic dXNlcjpwYXNzd29yZA==


###Get articles by page with sort by and sort order:
GET http://localhost:8080/api/v1/articles/page?pageSize=4&pageNo=0&sortDir=desc&sortBy=id
Authorization: Basic dXNlcjpwYXNzd29yZA==




### Delete an article by id:
DELETE http://localhost:8080/api/v1/articles/1




### population with some articles:
### Create an article:
POST http://localhost:8080/api/v1/articles
Authorization: Basic admin admin
Content-Type: application/json

{
  "category": "Chemistry",
  "title": "The second Chemistry Article",
  "content": "second article",
  "secondaryTitle": "the second chemistry article",
  "mainImg": "something",
  "mainImgDescription": "some image",
  "mainImgCredit": "no credit"
}

### Create an article:
POST http://localhost:8080/api/v1/articles
Authorization: Basic admin admin
Content-Type: application/json

{
  "category": "Chemistry",
  "title": "The third Chemistry Article",
  "content": "3'rd article",
  "secondaryTitle": "the third chemistry article",
  "mainImg": "something",
  "mainImgDescription": "some image",
  "mainImgCredit": "no credit"
}

### Create an article:
POST http://localhost:8080/api/v1/articles
Authorization: Basic admin admin
Content-Type: application/json

{
  "category": "Chemistry",
  "title": "The 4'th Chemistry Article",
  "content": "4'rh article",
  "secondaryTitle": "the fourth chemistry article",
  "mainImg": "something",
  "mainImgDescription": "some image",
  "mainImgCredit": "no credit"
}

### Create an article:
POST http://localhost:8080/api/v1/articles
Authorization: Basic admin admin
Content-Type: application/json

{
  "category": "Chemistry",
  "title": "The fifth Chemistry Article",
  "content": "5'th article",
  "secondaryTitle": "the fifth chemistry article",
  "mainImg": "something",
  "mainImgDescription": "some image",
  "mainImgCredit": "no credit"
}

### Create an article:
POST http://localhost:8080/api/v1/articles
Authorization: Basic admin admin
Content-Type: application/json

{
  "category": "Chemistry",
  "title": "The sixth Chemistry Article",
  "content": "6'th article",
  "secondaryTitle": "The sixth chemistry article",
  "mainImg": "something",
  "mainImgDescription": "some image",
  "mainImgCredit": "no credit"
}
